use_frameworks!
platform :ios, '9.0'

target 'HISmartPhone' do
	pod 'SnapKit', '~> 4.0.0'
	pod 'Charts'
	pod 'IQKeyboardManagerSwift'
  	pod 'BetterSegmentedControl', '~> 0.9'
  	pod 'BEMCheckBox'
	pod 'Charts'
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Alamofire', '~> 4.5'
	pod "ESTabBarController-swift"
	pod 'Firebase/Messaging'
end
